color0 #302221
color1 #d85c4e
color2 #d77875
color3 #c79d6b
color4 #bfc270
color5 #dea3a1
color6 #dcc2a3
color7 #f3f2f2
color8 #746363
color9 #d85c4e
color10 #d77875
color11 #c79d6b
color12 #bfc270
color13 #dea3a1
color14 #dcc2a3
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #231a1a
background            #231a1a
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #302221
active_border_color   #d77875
inactive_border_color #302221
url_color             #d77875

active_tab_foreground   #221b1b
active_tab_background   #d77875
inactive_tab_foreground #b6afaf
inactive_tab_background #302221
cursor_trail_color      #b6afaf
