color0 #242130
color1 #fd4663
color2 #8275d8
color3 #a66bc7
color4 #c270b7
color5 #a9a1de
color6 #c7a3dc
color7 #f2f2f3
color8 #676574
color9 #fd4663
color10 #8275d8
color11 #a66bc7
color12 #c270b7
color13 #a9a1de
color14 #c7a3dc
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1a23
background            #1b1a23
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #242130
active_border_color   #8275d7
inactive_border_color #242130
url_color             #8275d7

active_tab_foreground   #1b1a21
active_tab_background   #8275d7
inactive_tab_foreground #b0afb6
inactive_tab_background #242130
cursor_trail_color      #b0afb6
